---
title: "New Bars"
author: "Evan Daisy"
date: "5/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(datasets)
library(viridis)
library(maps)
library(leaflet)
```

```{r}
cities <- read_csv("cities_final.csv")
conservation <- read_csv("conservation_final.csv")
```

```{r}
url <- "https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)"
table <- (url %>%
  read_html() %>%
  html_nodes("table")) [[5]] %>%
  html_table() %>%
  janitor::clean_names()
```

```{r}
# Total Species By City
ggplot(cities, aes(x = City, y = Total)) + 
  geom_bar(stat = "Identity", aes(fill = City)) +
  labs(title = "Total Species By City") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  ylab("Total Species")
```

```{r}
# Stacked Bar Graph of Native and Introduced Species by City
ggplot(cities, aes(x = City, y = Species)) + 
  geom_bar(stat = "Identity", aes(fill = Origin)) +
  labs(title = "Native and Introduced Species By City") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  ylab("Total Species")
```

```{r}
# Map with the United States
ggplot(conservation, aes(x = long, y = lat, group = group, 
                         fill = total)) +
  geom_polygon(color = "black") +
  theme_void() +
  coord_fixed(ratio = 1.3) +
  labs(title = "Conservation Funding By Country*"
       , subtitle = "as of 2013"
       , fill = ""
       , caption = "*Regions in white have no data") +
  #scale_fill_continuous(low="thistle2", high="darkred",                      guide="colorbar", na.value="white")
  scale_fill_viridis(option = "plasma", direction = -1, na.value="white")
```

```{r}
# Map without the United States
no_us <- conservation %>%
  filter(region != "USA")
ggplot(no_us, aes(x = long, y = lat, group = group, 
                         fill = total)) +
  geom_polygon(color = "black") +
  theme_void() +
  coord_fixed(ratio = 1.3) +
  labs(title = "Conservation Funding By Country*"
       , subtitle = "as of 2013"
       , fill = ""
       , caption = "*Regions in white have no data") +
  #scale_fill_continuous(low="thistle2", high="darkred",                      guide="colorbar", na.value="white")
  scale_fill_viridis(option = "plasma", direction = -1, na.value="white")
```

```{r}
# Map of Log(funding)
ggplot(conservation, aes(x = long, y = lat, group = group, 
                         fill = log_funding)) +
  geom_polygon(color = "black") +
  theme_void() +
  coord_fixed(ratio = 1.3) +
  labs(title = "Conservation Funding By Country*"
       , subtitle = "as of 2013"
       , fill = ""
       , caption = "*Regions in white have no data") +
  #scale_fill_continuous(low="thistle2", high="darkred",                      guide="colorbar", na.value="white")
  scale_fill_viridis(option = "viridis", direction = -1, na.value="white")
```

```{r}
#Map of sqrt(funding)
ggplot(conservation, aes(x = long, y = lat, group = group, 
                         fill = sqrt_funding)) +
  geom_polygon(color = "black") +
  theme_void() +
  coord_fixed(ratio = 1.3) +
  labs(title = "Conservation Funding By Country*"
       , subtitle = "as of 2013, in millions of US dollars"
       , fill = ""
       , caption = "*Regions in white have no data") +
  #scale_fill_continuous(low="thistle2", high="darkred",                      guide="colorbar", na.value="white")
  scale_fill_viridis(option = "plasma", direction = -1, na.value="white")
```

```{r}
ggplot(conservation, aes(x = long, y = lat, group = group, 
                         fill = funding_per_GDP)) +
  geom_polygon(color = "black") +
  theme_void() +
  coord_fixed(ratio = 1.3) +
  labs(title = "Conservation Funding By Country as a Fraction of total GDP*"
       , subtitle = "as of 2013"
       , fill = ""
       , caption = "*Regions in white are missing GDP or funding data") +
  #scale_fill_continuous(low="thistle2", high="darkred",                      guide="colorbar", na.value="white")
  scale_fill_viridis(option = "plasma", direction = -1, na.value="white")
```






